remote_theme: just-the-docs/just-the-docs
title: Accrivo
description: Privacy-First Personal Finance App
url: https://inmksolutions.github.io/accrivo
# Just the Docs specific settings
color_scheme: dark # Or 'light' if you prefer
search_enabled: true
heading_anchors: true
